---
kind: pipeline
type: docker
name: default
trigger:
  event:
    - push

steps:

- name: build
  image: klakegg/hugo:ext-alpine
  commands:
  - hugo

- name: scp files
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: do_ssh_ip
    user: 
      from_secret: do_ssh_user
    key:
      from_secret: do_ssh_key
    port: 22
    command_timeout: 2m
    target: /data/www
    source:
      - public/
    strip_components: 1