languageCode: "en-us"
title: "rational human"
theme: hemingway2
baseURL: https://www.pietersartain.com/
refLinksErrorLevel: WARNING

params:
  social:
  -
    url: "https://github.com/pietersartain"
    fa_icon: "github"
  -
    url: "https://www.linkedin.com/in/pietersartain"
    fa_icon: "linkedin"
  -
    url: "/post/"
    fa_icon: "file-alt"
  -
    url: "/now"
    fa_icon: "address-card"
  # -
  #   url: "/index.xml"
  #   fa_icon: "rss"

# taxonomies:
#   tag: "tags"
#   category: "categories"

markup:
  goldmark:
    # extensions:
    #   definitionList: true
    #   footnote: true
    #   linkify: true
    #   strikethrough: true
    #   table: true
    #   taskList: true
    #   typographer: true
    # parser:
    #   attribute: true
    #   autoHeadingID: true
    #   autoHeadingIDType: github
    renderer:
      # hardWraps: false
      unsafe: true # Make inline HTML work.
      # xhtml: false
