languageCode = "en-us"
title = "rational human"
theme = "hemingway2"
baseURL = "https://www.pietersartain.com/"
copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a><span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/Text" property="dct:title" rel="dct:type"><a href="https://github.com/pietersartain/pietersartain.github.io">rational human</a></span> by <a xmlns:cc="http://creativecommons.org/ns#" href="pietersartain.com" property="cc:attributionName" rel="cc:attributionURL">Pieter Sartain</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.'

[[params.social]]
url = "https://github.com/pietersartain"
fa_icon = "fa-github"

[[params.social]]
url = "https://www.linkedin.com/in/pietersartain"
fa_icon = "fa-linkedin"

[[params.social]]
url = "https://twitter.com/pietersartain"
fa_icon = "fa-twitter"

[[params.social]]
url = "/post/"
fa_icon = "fa-file-text"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
